### ISSUE TITLE
Readme instructions for set up

### ISSUE THREAD

**Issue by seabbs** [explodecomputer/USSpensions-shiny#1]
Just ran through setting this up. 

Had trouble with the given git clone link.  Replaced it with the following and everything worked.

```
git clone https://github.com/explodecomputer/USSpensions-shiny.git

```

**Comment by explodecomputer** [comment]
thanks fixed

**Comment by seabbs** [comment]
Awesome - great work by the way.

**Comment by explodecomputer** [comment]
Thanks =] Just trying to get the new domain name to point to it but I always get confused with this stuff. You can see the live version here http://crashdown.epi.bris.ac.uk:8011 Any feedback very welcome
