### ISSUE TITLE
Add license info

### ISSUE THREAD

**Issue by jezcope** [explodecomputer/USSpensions-shiny#3]
This is a very cool app, thanks! The website notes that all the code is available under GPL v3, so it's probably worth including that in this repository. [Typically that involves](https://www.gnu.org/licenses/gpl-howto.html) including the text of the license in a file called `COPYING` or `LICENSE` and copy-pasting a notice at the top of each source file.

**Comment by explodecomputer** [comment]
Hi thank you very much for this, you're absolutely right, I've added the license info now =]
